### ISSUE TITLE
[🐛 Bug]: User provided secret key is not used when tests are running

### ISSUE THREAD

**Issue by rabi-siddique** [agoric-labs/synpress#40]
### 🔎 Have you searched existing issues to avoid duplicates?

- [X] I have made sure that my issue is not a duplicate.

### 🧪 Have you tested your code using latest version of Synpress?

- [X] I have made sure that my issue still exists on [latest version of Synpress](https://github.com/Synthetixio/synpress/releases).

### 💡 Are you able to provide enough information to be able to reproduce your issue locally?

- [X] I can provide enough details to reproduce my issue on local environment.

### Synpress version

3.8.1

### Node.js version

18.18.0

### Operating system

Linux Mint

### Run mode

Playwright + Synpress (as plugin)

### Are you running your tests inside docker? (if applicable)

- [ ] This issue could be related to docker.

### What happened?

I tried again with the right mnemonic:
When the users add a `SECRET_WORDS` env variable, the address shown in the tests is `agoric1p2aqakv3ulz4qfy2nut86j9gx0dx0yw09h96md`. It does not correspond to the mnemonic provided by the user. 

### How to reproduce the bug.

Add a `SECRET_WORDS` env variable. You will notice that in tests, the value `SECRET_WORDS` is not being used.

**Comment by Jorge-Lopes** [comment]
Greetings,

I am currently trying to use the synpress pkg to build and execute e2e tests on an dapp deployed in Agoric, more specifically [KREAd](https://github.com/Kryha/KREAd).

There are some questions related to this issue that I would like to clarify:
- the mnemonic set as `SECRET_WORDS` has to be `orbit bench unit task food shock brand bracket domain regular warfare company announce wheel grape trust sphere boy doctor half guard ritual three ecology`, and any other value passed to it will not be considered?
- are we free to use this account for our testing purposes or is this reserved for the Agoric team?

Thank you in advance.

**Comment by rabi-siddique** [comment]
> Greetings,
> 
> I am currently trying to use the synpress pkg to build and execute e2e tests on an dapp deployed in Agoric, more specifically [KREAd](https://github.com/Kryha/KREAd).
> 
> There are some questions related to this issue that I would like to clarify:
> 
> * the mnemonic set as `SECRET_WORDS` has to be `orbit bench unit task food shock brand bracket domain regular warfare company announce wheel grape trust sphere boy doctor half guard ritual three ecology`, and any other value passed to it will not be considered?
> * are we free to use this account for our testing purposes or is this reserved for the Agoric team?
> 
> Thank you in advance.

@Jorge-Lopes, currently, there's a known issue where the tests default to using the mnemonic `orbit bench unit task food shock brand bracket domain regular warfare company announces wheel grape trust sphere boy doctor half guard ritual three ecology`, regardless of the value set in the `.env` file for `SECRET_WORDS`. This mnemonic is intended for Agoric usage and will soon be replaced with a more appropriate one. So, it's best to use your own mnemonic for a wallet with sufficient funds for testing purposes.

To add your preferred mnemonic for testing, you can provide it as a parameter to the setupWallet function. For example:
```js
    cy.setupWallet({
        secretWords:
          'orbit bench unit task food shock brand bracket domain regular warfare company announce wheel grape trust sphere boy doctor half guard ritual three ecology',
        password: 'Test1234',
        newAccount: true,
        walletName: 'My Wallet 2',
        selectedChains: ['Agoric localhost', 'Secret Network'],
      }).
```

**Comment by Jorge-Lopes** [comment]
@rabi-siddique Thank you very much for your suggestion.
